Monster update
SETI/pds-julian pull request #2
Opened 2023-10-27 23:40 UTC by markshowalter

This has been on and off the back burner for a year or more. Don't even try to do a code compare. A vast array of new features. 100% code completion. Warning--unit tests take ~ 10 minutes to run, mainly because of the painfully exhaustive set of combinations of options tested in the *pyparser.py files.

2023-11-06 03:44 UTC, markshowalter commented
This is a monster-update on the monster update.

- I never before took a serious look at help(julian) appears to the user, and obviously it required some big cleanup. What I see now looks reasonable. The names of the individual source files are exposed, which is a minor issue because they were only for the purpose of organizing all the function definitions. In some cases, I renamed the source file so that it would be potentially clearer to the user. That's necessary because `help(julian)` only tells part of the story, and you have to type `help(julian.<name>)` to see the further details.

- Although `help(<name>)` hides symbols beginning with an underscore, there does not appear to be a way to hide entire source files. Nevertheless, the ones not needing exposure now begin with an underscore so that is at least a sign to the user not to bother with, for example,` help(julian._utils)`.

- Also to help with the appearance of help, I moved all the deprecated function names, left over from v1, to a new file called `DEPRECATED.py`. I think that makes some sense and it means that `help(julian.DEPRECATED)` will tell you about all those functions.

- The one leap seconds kernel is now in julian/assets, whereas the other random documents, not really needed for a distribution, are in the top-level documents subdirectory. If there is ever a "`naif0013.tls`" file, all you have to do is add it to` julian/assets` and everything should work with the new kernel.

- So _maybe_ there are advantages of pytest over unittest, but meanwhile you broke a lot of my workflow by deleting all the "`if __name__ == '__main__'`" sections at the bottom of my test files. In the future, please leave them.

- By the way, I am not sure how you got away without a file `tests/__init__.py`, given that there is an import of one function between the test files. For now, it seems workable that I will use `__init__.py` in place of what I used to call unittester.py. For my purposes, I can run all the tests with "`coverage run tests/__init__.py`". Crucially, I can also run the test files individually without much thought.

- I am not totally sold on coverage branch testing. There were a lot of places where I say something like:
```
    if validate:
        <perform test and maybe raise an exception>

```
If that's all the branch does, there's not really much point in proving that everything is OK if you skip the validation. That all being said, the coverage is now 100% and I only used "`# pragma: no branch`" in places where I really had to.

- I have come to appreciate why the world's Windows programmers are pissed off about int32 vs. int64. The number of places where this comes up is large, and sometimes workarounds are quite difficult. For example, there are numerous places where I need to convert an array-like to an array without necessarily knowing whether it will yield ints or floats. Normally, `np.asarray(arg)` does exactly what I want. Unfortunately, on Windows, I have to re-check to see if it converted to ints and, if so, repeat the call with an explicit dtype of "int64". Check out how I modified `_utils/_int()` if you're interested.

- This issue did reveal an unexpected bug, arising from the fact that integer math ops using integer arrays leave the dtype unchanged. This can have unintended consequences. 

```
In [1]: a = np.arange(10, dtype='uint8')

In [2]: b = a - 1

In [3]: b
Out[3]: array([255,   0,   1,   2,   3,   4,   5,   6,   7,   8], dtype=uint8)

```
The upshot is that now all int arrays are converted to int64 no matter what.

2023-11-06 20:35 UTC, rfrenchseti requested changes
I found the following bug:

```
>>> (day, sec, time_type) = julian.day_sec_from_string('JD2234567.123', timesys=True)
>>> t = julian.tai_from_day(day) + sec
>>> (day2, sec2) = julian.day_sec_from_tai(t)
>>> jd = julian.jd_from_day_sec(day2, sec2)
>>> day, sec, day2, sec2
(-216977, 53827.20001190901, -216977, 53827.20001220703)
>>> jd
2234568.123
```

2023-11-07 20:16 UTC, rfrenchseti commented
OPUS has been appropriately modified and all tests pass

2023-11-07 20:17 UTC, rfrenchseti approved these changes

2023-11-07 20:18 UTC, merged